permalink: /blog/:categories/:title/
relative_permalinks: false

exclude: ["README.md","CNAME"]
include: []
safe: false
pygments: true

title: davidcapello.com
author:
  name: David Capello
  email: davidcapello@gmail.com
  github: dacap
  twitter: davidcapello

production_url: https://davidcapello.com
files_url: https://github.com/dacap/dacap.github.io/releases/download/files
archive_path: /blog/
categories_path: /categories/
tags_path: /tags/
