permalink: /blog/:categories/:title/
relative_permalinks: false

exclude: ["README.md","CNAME"]
include: []
safe: true
pygments: true
plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from

title: davidcapello.com
author:
  name: David Capello
  email: david@igara.com
  github: dacap
  twitter: davidcapello

production_url: https://davidcapello.com
files_url: https://github.com/dacap/dacap.github.io/releases/download/files
forum_url: https://github.com/dacap/dacap.github.io/discussions
archive_path: /blog/
categories_path: /categories/
tags_path: /tags/
